TPI/config/routes.rb
Rails.application.routes.draw do

  resources :users
  devise_for :users, :skip => [:registrations], :path_prefix => 'auth'

  root to: 'professionals#index'

  resources :grids
  post 'grid_create', to: 'grids#grid_create'

  resources :professionals do
    member do
      delete 'cancel_all_appointments', action: 'destroy_all_appointments'
    end
    resources :appointments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

TPI/app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments, dependent: :delete_all
    validates :name, presence: true, format: {with: /\A[a-zA-Z]+\z/, message: 'must contain letters only'}, uniqueness: { case_sensitive: false }, length: {maximum: 50}

    def can_be_deleted?
        !appointments.where('date > ?', DateTime.now).exists?
    end
end

TPI/app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  load_and_authorize_resource

  # GET /professionals or /professionals.json
  def index
    @professionals = Professional.all
  end

  # GET /professionals/1 or /professionals/1.json
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals or /professionals.json
  def create
    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to @professional, notice: "Professional was successfully created." }
        format.json { render :show, status: :created, location: @professional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professionals/1 or /professionals/1.json
  def update
    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to @professional, notice: "Professional was successfully updated." }
        format.json { render :show, status: :ok, location: @professional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professionals/1 or /professionals/1.json
  def destroy
    respond_to do |format|
      if @professional.can_be_deleted?
        @professional.destroy
        format.html { redirect_to professionals_url, notice: "Professional was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to professionals_url, notice: "Professional has appointments. Can't be destroyed." }
        format.json { head :no_content }
      end
    end
  end

  def destroy_all_appointments
    @professional.appointments.destroy_all
    respond_to do |format|
      format.html { redirect_to professionals_url, notice: "Professional's future appointments were succesfully canceled." }
      format.json { head :no_content }
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:name)
    end
end

TPI/app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

TPI/app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= error_message(professional, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

TPI/app/views/professionals/edit.html.erb
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

TPI/app/views/professionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professionals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.name %></td>
        <td><%= link_to 'Show', professional %></td>
        <td><%= link_to 'Appointments', professional_appointments_path(professional) %></td>
        <% if can? :manage, Professional %>
          <td><%= link_to 'Edit', edit_professional_path(professional) %></td>
          <td><%= link_to 'Delete', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Download appointments grid</h3>
<%= form_for :grid, url: grid_create_path do |form| %>
  <%= form.label :date, "Select date:"%>
  <%= form.date_field :date, include_blank: true %>
  <%= form.collection_select :professional, @professionals, :id , :name, :include_blank => true%>
  <%= form.radio_button :type, 'week', :checked => true %> 
  <%= label :type, 'Week' %>
  <%= form.radio_button :type, 'day' %>
  <%= label :type, 'Day' %>
  <%= form.submit 'Download' %>
  <%= link_to 'Reset', professionals_url %>
<% end %>

<br>
<% if can? :create, Professional %>
  <%= link_to 'New Professional', new_professional_path %>
<% end %>
<% if can? :manage, User %>
  <%= link_to 'Users management', users_path %>
<% end %>

TPI/app/views/professionals/new.html.erb
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

TPI/app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>

<%= link_to 'Edit', edit_professional_path(@professional) %> |
<%= link_to 'Back', professionals_path %>