TPI/config/routes.rb
Rails.application.routes.draw do

  resources :users
  devise_for :users, :skip => [:registrations], :path_prefix => 'auth'

  root to: 'professionals#index'

  resources :grids
  post 'grid_create', to: 'grids#grid_create'

  resources :professionals do
    member do
      delete 'cancel_all_appointments', action: 'destroy_all_appointments'
    end
    resources :appointments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

TPI/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional

  validates :date, presence: true, future: true, shift: true
  validates :surname, presence: true, format: {with: /\A[a-zA-Z]+\z/, message: 'must contain letters only'}
  validates :name, presence: true, format: {with: /\A[a-zA-Z]+\z/, message: 'must contain letters only'}
  validates :phone, presence: true
  scope :filter_by_date, -> (date_f) {where("strftime('%Y-%m-%d', date) = ?", date_f)}

  def can_be_deleted?
    date > DateTime.now
  end

end

TPI/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource :professional
  load_and_authorize_resource :appointment, through: :professional

  # GET /appointments or /appointments.json
  def index
    @appointments = @professional.appointments
    # Solo trae a los appointments que dependan del professional

    if filter_params[:f].present?
      @appointments = @appointments.filter_by_date(filter_params[:f])
    end

    @f = filter_params[:f]
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = @professional.appointments.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = @professional.appointments.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to [@professional, @appointment], notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to [@professional, @appointment], notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    respond_to do |format|
      if @appointment.can_be_deleted?
        @appointment.destroy
        format.html { redirect_to professional_appointments_url, notice: "Appointment was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to professional_appointments_url, notice: "Can't cancel past appointments." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :surname, :name, :phone, :note)
    end

    def filter_params
      if params.key?(:filters)
        params.require(:filters).permit(:f) 
      else
        {}
      end
    end
end

TPI/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

TPI/app/views/appointments/_form.html.erb
<%= form_with(model: [professional, appointment]) do |form| %>
  <div>
    <p>
      <h4>Schedule shifts: 8:00 - 16:45</h4>
      (Each shift lasts 15 minutes)
    </p>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, start_year: Date.today.year, minute_step: 15, start_hour: 8, end_hour: 16 %>
    <%= error_message(appointment, :date) %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
    <%= error_message(appointment, :surname) %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= error_message(appointment, :name) %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
    <%= error_message(appointment, :phone) %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

TPI/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<%= link_to 'Show', [@professional, @appointment] %> |
<%= link_to 'Back', professional_appointments_path(@professional) %>

TPI/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<%= form_for :filters, url: professional_appointments_path(@professional), method: :get do |form| %>
  <%= form.label :f, "Filter by date:"%>
  <%= form.date_field :f, include_blank: true, value: @f %>
  <%= form.submit 'Filter'%>
  <%= link_to 'Reset', professional_appointments_path(@professional) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Surname</th>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date.strftime("%d/%m/%Y - %H:%Mhs") %></td>
        <td><%= appointment.surname %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.phone %></td>
        <td><%= link_to 'Show', [@professional, appointment] %></td>
        <% if can? :manage, Appointment %>
          <td><%= link_to 'Edit', edit_professional_appointment_path(@professional, appointment) %></td>
          <td><%= link_to 'Cancel', [@professional, appointment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :manage, Appointment %>
  <%= link_to 'New Appointment', new_professional_appointment_path(@professional) %>
  <%= link_to 'Cancel all', cancel_all_appointments_professional_path(@professional), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', professionals_path %>

TPI/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<%= link_to 'Back', professional_appointments_path(@professional) %>

TPI/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date.strftime("%d/%m/%Y - %H:%Mhs") %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<%= link_to 'Edit', edit_professional_appointment_path(@professional, @appointment) %> |
<%= link_to 'Back', professional_appointments_path(@professional) %>